// Minimal engine adapters for standalone logic tests. These do not simulate Unity animation or navigation.
using System;
using System.Collections.Generic;
namespace UnityEngine {
 public class SerializeField:Attribute {} public class HeaderAttribute:Attribute {public HeaderAttribute(string s){}} public class TooltipAttribute:Attribute {public TooltipAttribute(string s){}} public class RequireComponent:Attribute {public RequireComponent(Type t){}}
 public class GameObject { public string name="test"; public Transform transform=new Transform(); public Dictionary<Type,object> components=new Dictionary<Type,object>(); public T GetComponent<T>() where T:class {object x; return components.TryGetValue(typeof(T),out x)?x as T:null;} }
 public class MonoBehaviour {public GameObject gameObject=new GameObject(); public Transform transform {get{return gameObject.transform;}} public T GetComponent<T>() where T:class{return gameObject.GetComponent<T>();}}
 public class Transform {public Vector3 position; public Vector3 forward=new Vector3(0,0,1); public Quaternion rotation;}
 public struct Vector3 {public float x,y,z; public Vector3(float a,float b,float c){x=a;y=b;z=c;} public static Vector3 up {get{return new Vector3(0,1,0);}} public float sqrMagnitude{get{return x*x+y*y+z*z;}} public float magnitude{get{return (float)Math.Sqrt(sqrMagnitude);}} public Vector3 normalized{get{return magnitude==0?this:new Vector3(x/magnitude,y/magnitude,z/magnitude);}} public static Vector3 operator -(Vector3 a,Vector3 b){return new Vector3(a.x-b.x,a.y-b.y,a.z-b.z);} public static float Distance(Vector3 a,Vector3 b){return (a-b).magnitude;} public static float Angle(Vector3 a,Vector3 b){return 0;} public static float SignedAngle(Vector3 a,Vector3 b,Vector3 c){return 0;} }
 public struct Quaternion {public static Quaternion LookRotation(Vector3 v){return new Quaternion();} public static Quaternion RotateTowards(Quaternion a,Quaternion b,float c){return b;}}
 public static class Mathf {public static float Max(float a,float b){return Math.Max(a,b);} public static float Min(float a,float b){return Math.Min(a,b);}}
 public static class Time {public static float deltaTime=0.02f; public static float time; public static int frameCount;}
 public static class Random {public static int Range(int a,int b){return a;}}
 public static class Debug {public static void LogWarning(object m,object c=null){} public static void LogError(object m,object c=null){} public static void Log(object m,object c=null){}}
 public struct AnimatorStateInfo {public string Name,Tag; public float normalizedTime; public bool IsName(string n){return Name==n;} public bool IsTag(string tag){return Tag==tag;} public int fullPathHash{get{return Animator.StringToHash(Name??"");}} }
 public class Animator {public int layerCount=1;public bool enabled=true,isActiveAndEnabled=true,applyRootMotion=true; public float speed=1; public string name="animator"; public AnimatorStateInfo Current,Next; public bool Transition,StateExists=true; public int CrossFades; public string LastCrossFade; public Dictionary<int,float> Floats=new Dictionary<int,float>(); public Dictionary<int,bool> Bools=new Dictionary<int,bool>(); public static int StringToHash(string s){return s.GetHashCode();} public void SetBool(int h,bool v){Bools[h]=v;} public void SetFloat(int h,float v){Floats[h]=v;} public void SetFloat(int h,float v,float d,float t){Floats[h]=v;} public AnimatorStateInfo GetCurrentAnimatorStateInfo(int l){return Current;} public AnimatorStateInfo GetNextAnimatorStateInfo(int l){return Next;} public bool IsInTransition(int l){return Transition;} public bool HasState(int l,int h){return StateExists;} public void CrossFadeInFixedTime(string n,float d,int l){LastCrossFade=n;CrossFades++;} public void CrossFadeInFixedTime(string n,float d,int l,float t){CrossFadeInFixedTime(n,d,l);} }
}
namespace UnityEngine.AI {
 public enum NavMeshPathStatus {PathComplete,PathPartial,PathInvalid}
 public class NavMeshAgent {public bool enabled=true,isActiveAndEnabled=true,isOnNavMesh=true,hasPath=true,pathPending,isStopped,updatePosition,updateRotation,AcceptDestination=true; public float remainingDistance=10,stoppingDistance; public UnityEngine.Vector3 destination,nextPosition,steeringTarget=new UnityEngine.Vector3(0,0,10),desiredVelocity=new UnityEngine.Vector3(0,0,3.5f); public NavMeshPathStatus pathStatus=NavMeshPathStatus.PathComplete; public bool SetDestination(UnityEngine.Vector3 v){destination=v;return AcceptDestination;} public void ResetPath(){hasPath=false;}}
}
namespace Opsive.Shared.Utility {public class Category:Attribute{public Category(string s){}} public class Description:Attribute{public Description(string s){}}}
namespace Opsive.GraphDesigner.Runtime.Variables {public class SharedVariable<T> {public T Value; public static implicit operator SharedVariable<T>(T value){return new SharedVariable<T>{Value=value};}}}
namespace Opsive.BehaviorDesigner.Runtime.Tasks {public enum TaskStatus {Failure,Success,Running}}
namespace Opsive.BehaviorDesigner.Runtime.Tasks.Actions {public class TargetGameObjectAction {protected UnityEngine.GameObject m_ResolvedGameObject; protected virtual void InitializeTarget(){} public virtual void OnStart(){} public virtual Opsive.BehaviorDesigner.Runtime.Tasks.TaskStatus OnUpdate(){return Opsive.BehaviorDesigner.Runtime.Tasks.TaskStatus.Success;} public virtual void OnEnd(){} public virtual void Reset(){} }}