using System;
using System.Reflection;
using UnityEngine;
using UnityEngine.AI;
using Opsive.GraphDesigner.Runtime.Variables;
using Opsive.BehaviorDesigner.Runtime.Tasks;
public static class EnemyChaseRegression {
 static void Set(object o,string name,object value){for(var t=o.GetType();t!=null;t=t.BaseType){var f=t.GetField(name,BindingFlags.Instance|BindingFlags.NonPublic);if(f!=null){f.SetValue(o,value);return;}}throw new Exception("Missing field "+name);}
 static void Check(bool ok,string message){if(!ok)throw new Exception(message);}
 class Rig {public EnemyAIMovementController Controller=new EnemyAIMovementController();public Animator Animator=new Animator();public NavMeshAgent Agent=new NavMeshAgent();public GameObject Target=new GameObject();public ChaseWithMovement Task=new ChaseWithMovement(); public Rig(){Set(Controller,"agent",Agent);Set(Controller,"animator",Animator);Controller.GetType().GetMethod("Awake",BindingFlags.Instance|BindingFlags.NonPublic).Invoke(Controller,null);Set(Task,"movementController",Controller);Set(Task,"m_ResolvedGameObject",Controller.gameObject);Set(Task,"m_Target",new SharedVariable<GameObject>{Value=Target});Task.OnStart();}public TaskStatus Step(float distance){Target.transform.position=new Vector3(0,0,distance);Agent.remainingDistance=distance;return Task.OnUpdate();}public float Movement{get{return Animator.Floats[Animator.StringToHash("Movement")];}}}
 public static string Run(){int count=0;
  var r=new Rig(); Check(r.Step(10)==TaskStatus.Running,"Far chase should run");Check(r.Movement==2,"Far chase must select run animation (2)"); Check(r.Step(5.5f)==TaskStatus.Running&&r.Movement==2,"Running must persist in hysteresis band");Check(r.Step(4)==TaskStatus.Running&&r.Movement==1,"Near chase must select walk animation (1)");Check(r.Step(5.5f)==TaskStatus.Running&&r.Movement==1,"Walking must persist in hysteresis band");count++;
  Check(r.Step(0.5f)==TaskStatus.Running,"Arrival must wait for stop, not succeed immediately");Check(r.Animator.CrossFades==1&&r.Animator.LastCrossFade=="Base Layer.Movement.急停.Run_End","Arrival must start configured stop once");Check(!r.Animator.applyRootMotion,"Chase stop must disable root motion while the stop animation plays");r.Animator.Current=new AnimatorStateInfo{Name="Base Layer.Idle",normalizedTime=4};Check(r.Step(10)==TaskStatus.Running,"Idle before stop entry cannot count as completion");Check(r.Animator.CrossFades==1,"Stop must not restart each frame");r.Animator.Current=new AnimatorStateInfo{Name="Base Layer.Movement.急停.Run_End",normalizedTime=0.5f};Check(r.Step(10)==TaskStatus.Running,"Stop must play fully even when target moves away");r.Animator.Current=new AnimatorStateInfo{Name="Base Layer.Movement.急停.Run_End",normalizedTime=1.1f};r.Animator.Transition=true;Check(r.Step(10)==TaskStatus.Running,"Must wait through exit transition");r.Animator.Current=new AnimatorStateInfo{Name="Base Layer.Idle",normalizedTime=0};r.Animator.Transition=false;Check(r.Step(10)==TaskStatus.Success,"Completed stop returning to Idle must succeed");Check(r.Animator.applyRootMotion,"Completed chase stop must restore root motion");count++;
  r.Task.OnEnd();Check(r.Animator.applyRootMotion,"Ending chase stop early must restore root motion");r.Task.OnStart();r.Agent.hasPath=true;Check(r.Step(4)==TaskStatus.Running&&r.Movement==1,"New repeat must reset stop and gait state");count++;
  r=new Rig();r.Agent.isOnNavMesh=false;Check(r.Step(10)==TaskStatus.Failure,"Unavailable navigation must fail rather than run forever");count++;
  r=new Rig();r.Animator.StateExists=false;Check(r.Step(0.5f)==TaskStatus.Failure,"Missing stop state cannot succeed or wait forever");count++;
  r=new Rig();Set(r.Task,"m_Run",new SharedVariable<bool>{Value=false});Check(r.Step(10)==TaskStatus.Running&&r.Movement==1,"Disabled running must retain walk compatibility");count++;
  r=new Rig();r.Agent.pathStatus=NavMeshPathStatus.PathPartial;r.Agent.remainingDistance=0.2f;r.Target.transform.position=new Vector3(0,0,10);Check(r.Task.OnUpdate()==TaskStatus.Failure,"Partial path endpoint is not arrival at target");count++;
  r=new Rig();r.Agent.pathStatus=NavMeshPathStatus.PathInvalid;Check(r.Step(10)==TaskStatus.Failure,"Invalid path cannot report arrival");count++;
  r=new Rig();r.Agent.pathPending=true;r.Agent.hasPath=false;r.Agent.remainingDistance=0;r.Target.transform.position=new Vector3(0,0,10);Check(r.Task.OnUpdate()==TaskStatus.Running&&r.Animator.CrossFades==0,"Pending path with zero distance cannot trigger stop");count++;
  r=new Rig();r.Agent.hasPath=false;r.Agent.pathPending=false;r.Agent.remainingDistance=0;Check(r.Step(10)==TaskStatus.Running&&!r.Controller.LastMoveFailed&&r.Movement==2,"Fresh destination without a ready path must wait instead of failing");count++;
  r=new Rig();Check(r.Step(0.5f)==TaskStatus.Running,"Stop should start");r.Animator.Current=new AnimatorStateInfo{Name="Base Layer.Movement.急停.Run_End",normalizedTime=0.4f};r.Task.OnUpdate();r.Animator.Current=new AnimatorStateInfo{Name="Base Layer.Idle",normalizedTime=0};Check(r.Task.OnUpdate()==TaskStatus.Running,"Interrupted early stop cannot masquerade as full completion");count++;
  r=new Rig();r.Step(0.5f);Set(r.Task,"m_Target",new SharedVariable<GameObject>{Value=null});Check(r.Task.OnUpdate()==TaskStatus.Running,"Target loss during stop must not skip stop");r.Animator.isActiveAndEnabled=false;Check(r.Task.OnUpdate()==TaskStatus.Failure,"Disabled animator cannot keep stop waiting indefinitely");count++;
  r=new Rig();Check(!r.Controller.MoveTo((GameObject)null,1,false)&&r.Controller.LastMoveFailed,"Null movement target must report failure");count++;
  r=new Rig();Check(r.Agent.updatePosition,"Enemy movement must let NavMeshAgent drive transform position by default");count++;
  return "PASS: "+count+" scenarios (gait/hysteresis, stop lifecycle, repeat reset, unavailable navigation, missing stop, walk only)";
 }
}
