//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Game.proto
namespace GameProtocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MoveInput")]
  public partial class MoveInput : global::ProtoBuf.IExtensible
  {
    public MoveInput() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PlayerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private int _frame;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"frame", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Frame
    {
      get { return _frame; }
      set { _frame = value; }
    }

    private float _horizontal = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"horizontal", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float Horizontal
    {
      get { return _horizontal; }
      set { _horizontal = value; }
    }

    private float _vertical = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"vertical", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float Vertical
    {
      get { return _vertical; }
      set { _vertical = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"CSID")]
    public enum CSID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TCP_LOGIN", Value=1)]
      TCPLOGIN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TCP_REQUEST_MATCH", Value=10)]
      TCPREQUESTMATCH = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TCP_CANCEL_MATCH", Value=11)]
      TCPCANCELMATCH = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UDP_BATTLE_READY", Value=51)]
      UDPBATTLEREADY = 51,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UDP_UP_PLAYER_OPERATIONS", Value=53)]
      UDPUPPLAYEROPERATIONS = 53,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UDP_UP_DELTA_FRAMES", Value=55)]
      UDPUPDELTAFRAMES = 55,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UDP_UP_GAME_OVER", Value=57)]
      UDPUPGAMEOVER = 57
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SCID")]
    public enum SCID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TCP_RESPONSE_LOGIN", Value=1)]
      TCPRESPONSELOGIN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TCP_RESPONSE_REQUEST_MATCH", Value=10)]
      TCPRESPONSEREQUESTMATCH = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TCP_RESPONSE_CANCEL_MATCH", Value=11)]
      TCPRESPONSECANCELMATCH = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TCP_ENTER_BATTLE", Value=50)]
      TCPENTERBATTLE = 50,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UDP_BATTLE_START", Value=51)]
      UDPBATTLESTART = 51,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UDP_DOWN_FRAME_OPERATIONS", Value=53)]
      UDPDOWNFRAMEOPERATIONS = 53,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UDP_DOWN_DELTA_FRAMES", Value=55)]
      UDPDOWNDELTAFRAMES = 55,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UDP_DOWN_GAME_OVER", Value=57)]
      UDPDOWNGAMEOVER = 57
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"TeamType")]
    public enum TeamType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO", Value=0)]
      NO = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEAM1", Value=1)]
      TEAM1 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEAM2", Value=2)]
      TEAM2 = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEAM3", Value=3)]
      TEAM3 = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEAM4", Value=4)]
      TEAM4 = 4
    }
  
}