//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Game.proto
namespace GameProtocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TcpLogin")]
  public partial class TcpLogin : global::ProtoBuf.IExtensible
  {
    public TcpLogin() {}
    
    private string _token;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TcpResponseLogin")]
  public partial class TcpResponseLogin : global::ProtoBuf.IExtensible
  {
    public TcpResponseLogin() {}
    
    private bool _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _uid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private int _udpPort;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"udpPort", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int udpPort
    {
      get { return _udpPort; }
      set { _udpPort = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TcpResponseRequestMatch")]
  public partial class TcpResponseRequestMatch : global::ProtoBuf.IExtensible
  {
    public TcpResponseRequestMatch() {}
    
    private bool _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TcpRequestMatch")]
  public partial class TcpRequestMatch : global::ProtoBuf.IExtensible
  {
    public TcpRequestMatch() {}
    
    private int _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private int _roleId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TcpResponseCancelMatch")]
  public partial class TcpResponseCancelMatch : global::ProtoBuf.IExtensible
  {
    public TcpResponseCancelMatch() {}
    
    private bool _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TcpRequestCancelMatch")]
  public partial class TcpRequestCancelMatch : global::ProtoBuf.IExtensible
  {
    public TcpRequestCancelMatch() {}
    
    private int _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleUserInfo")]
  public partial class BattleUserInfo : global::ProtoBuf.IExtensible
  {
    public BattleUserInfo() {}
    
    private int _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private int _battleID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"battleID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int battleID
    {
      get { return _battleID; }
      set { _battleID = value; }
    }
    private int _roleID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"roleID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roleID
    {
      get { return _roleID; }
      set { _roleID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TcpEnterBattle")]
  public partial class TcpEnterBattle : global::ProtoBuf.IExtensible
  {
    public TcpEnterBattle() {}
    
    private int _randSeed;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"randSeed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int randSeed
    {
      get { return _randSeed; }
      set { _randSeed = value; }
    }
    private readonly global::System.Collections.Generic.List<GameProtocol.BattleUserInfo> _battleUserInfo = new global::System.Collections.Generic.List<GameProtocol.BattleUserInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"battleUserInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<GameProtocol.BattleUserInfo> battleUserInfo
    {
      get { return _battleUserInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UdpBattleReady")]
  public partial class UdpBattleReady : global::ProtoBuf.IExtensible
  {
    public UdpBattleReady() {}
    
    private int _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private int _battleID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"battleID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int battleID
    {
      get { return _battleID; }
      set { _battleID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UdpBattleStart")]
  public partial class UdpBattleStart : global::ProtoBuf.IExtensible
  {
    public UdpBattleStart() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerOperation")]
  public partial class PlayerOperation : global::ProtoBuf.IExtensible
  {
    public PlayerOperation() {}
    
    private int _battleID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"battleID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int battleID
    {
      get { return _battleID; }
      set { _battleID = value; }
    }
    private int _move;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"move", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int move
    {
      get { return _move; }
      set { _move = value; }
    }

    private int _operationID = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"operationID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int operationID
    {
      get { return _operationID; }
      set { _operationID = value; }
    }

    private GameProtocol.RightOpType _rightOperation = GameProtocol.RightOpType.noop;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"rightOperation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(GameProtocol.RightOpType.noop)]
    public GameProtocol.RightOpType rightOperation
    {
      get { return _rightOperation; }
      set { _rightOperation = value; }
    }

    private int _operationValue1 = (int)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"operationValue1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int operationValue1
    {
      get { return _operationValue1; }
      set { _operationValue1 = value; }
    }

    private int _operationValue2 = (int)0;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"operationValue2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int operationValue2
    {
      get { return _operationValue2; }
      set { _operationValue2 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UdpUpPlayerOperations")]
  public partial class UdpUpPlayerOperations : global::ProtoBuf.IExtensible
  {
    public UdpUpPlayerOperations() {}
    
    private int _mesID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mesID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mesID
    {
      get { return _mesID; }
      set { _mesID = value; }
    }
    private GameProtocol.PlayerOperation _operation;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"operation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public GameProtocol.PlayerOperation operation
    {
      get { return _operation; }
      set { _operation = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AllPlayerOperation")]
  public partial class AllPlayerOperation : global::ProtoBuf.IExtensible
  {
    public AllPlayerOperation() {}
    
    private readonly global::System.Collections.Generic.List<GameProtocol.PlayerOperation> _operations = new global::System.Collections.Generic.List<GameProtocol.PlayerOperation>();
    [global::ProtoBuf.ProtoMember(1, Name=@"operations", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<GameProtocol.PlayerOperation> operations
    {
      get { return _operations; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UdpDownFrameOperations")]
  public partial class UdpDownFrameOperations : global::ProtoBuf.IExtensible
  {
    public UdpDownFrameOperations() {}
    
    private int _frameID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"frameID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int frameID
    {
      get { return _frameID; }
      set { _frameID = value; }
    }
    private GameProtocol.AllPlayerOperation _operations;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"operations", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public GameProtocol.AllPlayerOperation operations
    {
      get { return _operations; }
      set { _operations = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UdpUpDeltaFrames")]
  public partial class UdpUpDeltaFrames : global::ProtoBuf.IExtensible
  {
    public UdpUpDeltaFrames() {}
    
    private int _battleID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"battleID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int battleID
    {
      get { return _battleID; }
      set { _battleID = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _frames = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"frames", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> frames
    {
      get { return _frames; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UdpDownDeltaFrames")]
  public partial class UdpDownDeltaFrames : global::ProtoBuf.IExtensible
  {
    public UdpDownDeltaFrames() {}
    
    private readonly global::System.Collections.Generic.List<GameProtocol.UdpDownFrameOperations> _framesData = new global::System.Collections.Generic.List<GameProtocol.UdpDownFrameOperations>();
    [global::ProtoBuf.ProtoMember(1, Name=@"framesData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<GameProtocol.UdpDownFrameOperations> framesData
    {
      get { return _framesData; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UdpUpGameOver")]
  public partial class UdpUpGameOver : global::ProtoBuf.IExtensible
  {
    public UdpUpGameOver() {}
    
    private int _battleID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"battleID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int battleID
    {
      get { return _battleID; }
      set { _battleID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UdpDownGameOver")]
  public partial class UdpDownGameOver : global::ProtoBuf.IExtensible
  {
    public UdpDownGameOver() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MoveInput")]
  public partial class MoveInput : global::ProtoBuf.IExtensible
  {
    public MoveInput() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private int _frame;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"frame", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int frame
    {
      get { return _frame; }
      set { _frame = value; }
    }

    private float _horizontal = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"horizontal", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float horizontal
    {
      get { return _horizontal; }
      set { _horizontal = value; }
    }

    private float _vertical = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"vertical", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float vertical
    {
      get { return _vertical; }
      set { _vertical = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"CSID")]
    public enum CSID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TCP_LOGIN", Value=1)]
      TCP_LOGIN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TCP_REQUEST_MATCH", Value=10)]
      TCP_REQUEST_MATCH = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TCP_CANCEL_MATCH", Value=11)]
      TCP_CANCEL_MATCH = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UDP_BATTLE_READY", Value=51)]
      UDP_BATTLE_READY = 51,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UDP_UP_PLAYER_OPERATIONS", Value=53)]
      UDP_UP_PLAYER_OPERATIONS = 53,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UDP_UP_DELTA_FRAMES", Value=55)]
      UDP_UP_DELTA_FRAMES = 55,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UDP_UP_GAME_OVER", Value=57)]
      UDP_UP_GAME_OVER = 57
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SCID")]
    public enum SCID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TCP_RESPONSE_LOGIN", Value=1)]
      TCP_RESPONSE_LOGIN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TCP_RESPONSE_REQUEST_MATCH", Value=10)]
      TCP_RESPONSE_REQUEST_MATCH = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TCP_RESPONSE_CANCEL_MATCH", Value=11)]
      TCP_RESPONSE_CANCEL_MATCH = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TCP_ENTER_BATTLE", Value=50)]
      TCP_ENTER_BATTLE = 50,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UDP_BATTLE_START", Value=51)]
      UDP_BATTLE_START = 51,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UDP_DOWN_FRAME_OPERATIONS", Value=53)]
      UDP_DOWN_FRAME_OPERATIONS = 53,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UDP_DOWN_DELTA_FRAMES", Value=55)]
      UDP_DOWN_DELTA_FRAMES = 55,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UDP_DOWN_GAME_OVER", Value=57)]
      UDP_DOWN_GAME_OVER = 57
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"TeamType")]
    public enum TeamType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO", Value=0)]
      NO = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEAM1", Value=1)]
      TEAM1 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEAM2", Value=2)]
      TEAM2 = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEAM3", Value=3)]
      TEAM3 = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEAM4", Value=4)]
      TEAM4 = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"RightOpType")]
    public enum RightOpType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"noop", Value=0)]
      noop = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"rop1", Value=1)]
      rop1 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"rop2", Value=2)]
      rop2 = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"rop3", Value=3)]
      rop3 = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"rop4", Value=4)]
      rop4 = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"rop5", Value=5)]
      rop5 = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"rop6", Value=6)]
      rop6 = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"rop7", Value=7)]
      rop7 = 7
    }
  
}