package GameProtocol;

enum CSID{
	TCP_LOGIN = 1;						//TcpLogin

	TCP_REQUEST_MATCH = 10;				//TcpRequestMatch
	TCP_CANCEL_MATCH = 11;				//TcpCancelMatch

	UDP_BATTLE_READY = 51;				//UdpBattleReady
	UDP_UP_PLAYER_OPERATIONS = 53;		//UdpUpPlayerOperations
	UDP_UP_DELTA_FRAMES = 55;			//UdpUpDeltaFrames
	UDP_UP_GAME_OVER = 57;				//UdpUpGameOver
}

enum SCID{
	TCP_RESPONSE_LOGIN = 1;				//TcpResponseLogin

	TCP_RESPONSE_REQUEST_MATCH = 10;	//TcpResponseRequestMatch
	TCP_RESPONSE_CANCEL_MATCH = 11;		//TcpResponseCancelMatch

	TCP_ENTER_BATTLE = 50;				//TcpEnterBattle
	UDP_BATTLE_START = 51;				//UdpBattleStart
	UDP_DOWN_FRAME_OPERATIONS = 53;		//UdpDownFrameOperations
	UDP_DOWN_DELTA_FRAMES = 55;			//UdpDownDeltaFrames
	UDP_DOWN_GAME_OVER = 57;			//UdpDownGameOver
}

enum TeamType
{
	NO = 0;
	TEAM1 = 1;
	TEAM2 = 2;
	TEAM3 = 3;
	TEAM4 = 4;
}

message TcpLogin{
	required string token = 1;
}

//登录相关
message TcpResponseLogin{
	required bool result = 1;
	required int32 uid = 2;
	required int32 udpPort = 3;
}

//匹配相关
message TcpResponseRequestMatch{
	required bool result = 1;
}

message TcpRequestMatch{
	required int32 uid = 1;
	required int32 roleId = 2;
}

message TcpResponseCancelMatch{
	required bool result = 1;
}

message TcpRequestCancelMatch{
	required int32 uid = 1;
}

//战场相关
message TcpEnterBattle{
	required bool result = 1;
}

//角色移动
message MoveInput{
    required int32 playerId = 1;
    required int32 frame = 2;
    optional float horizontal = 3;
    optional float vertical = 4;
}